### ISSUE TITLE
Load NVML lib at runtime

### ISSUE THREAD

**Issue by Cldfire** [Cldfire/nvml-wrapper#12]
Right now this crate can only be used as an optional compile-time dependency on Linux and / or Windows. This makes it impossible both to build a binary that can be distributed cross-platform and to build a binary that can decide at runtime whether or not it is possible to get GPU info.

This crate needs to be moved to a dlopen-style approach where symbols are obtained at runtime, something that is unfortunately going to be a lot of work. It'll hopefully become somewhat tractable if and when [this bindgen issue](https://github.com/rust-lang/rust-bindgen/issues/1541) is resolved.

If I have the time and motivation + bindgen or some other tool makes the process more streamlined, I will invest the time into re-working the crate.

(Note that I may also end up dropping a lot of the more niche API surface upon making this migration in order to focus my time on supporting the more commonly-used functionality.)

**Comment by jgrund** [comment]
Looks like #1846 has landed and is incorporated into the 0.5.6 release of bindgen

**Comment by Cldfire** [comment]
Wonderful! Thanks for the heads up.

I'll give the new bindgen feature a poke tonight and see what using it looks like in practice.

**Comment by Cldfire** [comment]
Support for loading the NVML library at runtime has landed in master; thanks to @RDruon for all their work in #14!

There are some things left for me to take care of before I can release `0.7.0`, but it shouldn't be too long from now.

**Comment by Cldfire** [comment]
`0.7.0` has been published!
