### ISSUE TITLE
Any way to build without /usr/lib?

### ISSUE THREAD

**Issue by bbigras** [Cldfire/nvml-wrapper#13]
My libs are in a non-standard location. I'm trying to build zenith which uses this crate.

Anything I can do? Like use an env var?

**Comment by Cldfire** [comment]
I was able to build and run the tests for this crate successfully just now with my libs moved to a non-standard directory using:

`LD_LIBRARY_PATH=/path/to/lib/folder cargo test`

Give that a try and let me know if it helps :slightly_smiling_face:

**Comment by bbigras** [comment]
Oh, you need to enable the "nvidia" feature. It's disabled by default.

**Comment by Cldfire** [comment]
Ah, yeah.

That's because right now it's not possible to compile with this crate as a dependency and decide at runtime whether or not it's possible to get GPU information. I've opened #12 to track supporting that.

Thanks for opening an issue! If run into any further issues just let me know :+1:

**Comment by bbigras** [comment]
Perfect. Thank you very much for your time.
