### ISSUE TITLE
Accept more variants of lib name or make internal init public

### ISSUE THREAD

**Issue by xd009642** [Cldfire/nvml-wrapper#17]
So I attempted to run a tool made using this in an nvidia based docker image and found it didn't work. Further investigation showed that the image had `libnvidia-ml.so.1` symlinked to `libnvidia-ml.so.450.80.02` but hadn't created a `libnvidia-ml.so`. 

I can create the symlink myself as a workaround, it's just the tool may be copied from this image as a base image an image built off the same nvidia base image without the symlink so it just adds a mild inconvenience to every user. Also when using a non-root user for security reasons I won't be able to create the symlink from my tool either :disappointed:

**Comment by xd009642** [comment]
Oh never mind just found the Nvml builder, that solves my issues. Sorry for the noise!

**Comment by Cldfire** [comment]
> Oh never mind just found the Nvml builder, that solves my issues. Sorry for the noise!

No worries! I'm glad the builder helped out, this sort of situation is exactly why I added it :)
