### ISSUE TITLE
nvmlDeviceSetGpuLockedClocks vs nvmlDeviceSetMemoryLockedClocks

### ISSUE THREAD

**Issue by benrod3k** [Cldfire/nvml-wrapper#26]
There's currently no `nvmlDeviceSetMemoryLockedClocks` available in `nvml-wrapper-rs\src\bindings.rs`. How could I make it available? Glad to help if it's a good newbie task. 

refs: https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceCommands.html#group__nvmlDeviceCommands_1g3cab0aaf0e46aa76469f18707e5867f1

**Comment by benrod3k** [comment]
Managed to make it work. Please have a look, thks. @Cldfire

**Comment by Cldfire** [comment]
`0.8.0` has been released with these functions wrapped :smile:
