### ISSUE TITLE
GPU Temp sensors

### ISSUE THREAD

**Issue by Snazzie** [Cldfire/nvml-wrapper#28]
Is there a way to get more GPU temp sensors?  i.e Core, hotspot, mem junction.
Currently i only see `nvml::enum_wrappers::device::TemperatureSensor::Gpu` which i assume is Core?

**Comment by Cldfire** [comment]
Hi! Where are you seeing those temp sensors you mention? Presumably there's a newer NVML header with more sensor definitions and I just haven't updated this library yet.

**Comment by Snazzie** [comment]
Never worked with nvml before 😓 
Had a look at nvml doc, yeah GPU seems like the only enum available.
i saw `NVML_TEMPERATURE_THRESHOLD_MEM_MAX` under enum `nvmlTemperatureThresholds_t`? maybe thats of use to me.
https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceEnumvs.html#group__nvmlDeviceEnumvs_1g2650b526841fa38b8f293c2d509a1de0

I had a look inside LibreHardwareLib (im currently using and looking to replace with nvml in my project), it seems to be getting those sensors via names using nvapi. So i think this issue is invalid for this repo 😅
